---
title: "Child_Exercise_Thesis"
author: "Sankhadip"
date: "5/2/2020"
output: html_document
---

```{r, eval=T, echo=FALSE}

suppressMessages(library(tidyverse))
suppressMessages(library(ggplot2))
suppressMessages(library(GGally))
suppressMessages(library(lubridate))
suppressMessages(library(readxl))
suppressMessages(library(plotly))
suppressMessages(library(lubridate))
suppressMessages(library(sitar))

```

Renaming Column Names for easy code handling and Cleaning Data

```{r}
e <- read_excel("~/SharedFiles/ST606/2020/data/Exercise/fit_database_anthropometric_all.xlsx")
e_normal <- read_excel("~/SharedFiles/ST606/2020/data/Exercise/fit_database_exercise_normal.xlsx")


#Renaming Variables

names(e)[names(e)=='measurement date']<- 'measurement_date'
names(e)[names(e)=='age (years)']<- 'age_years'
names(e)[names(e)=='age bin']<- 'age_bin'
#names(e)[names(e)=='z-category (WHO)']<- 'z_cat_WHO'
names(e)[length(e)]<-"z_cat_WHO"
names(e)[9]<-"z_score_WHO"
names(e)[6]<-"height_cm"
names(e)[7]<-"weight_kg"

#Dealing with NAs
ena<-na.omit(e)
any(is.na(ena$z_cat_WHO))

```


```{r}

#Changing Data Types
ena <- ena %>%
  mutate(gender = as.factor(gender),
         z_cat_WHO=as.factor(z_cat_WHO),
         measurement_date=as.Date(measurement_date),
         BMI = as.numeric(BMI),
         z_score_WHO=as.numeric(z_score_WHO),
         height_cm=as.numeric(height_cm),
         weight_kg=as.numeric(weight_kg))

#Removing "NA" Characters
ena$observation <- 1:nrow(ena)
x<-ena[ena$z_cat_WHO=="NA",]
y<-x$observation
ena<-ena[-y,]

#Adding additional column
ena$year <- year(ena$measurement_date)

```

Diving data as per Year

```{r}

ena_2007 <- filter(ena, year(measurement_date) == 2007)
ena_2008 <- filter(ena, year(measurement_date) == 2008)
ena_2009 <- filter(ena, year(measurement_date) == 2009)
ena_2010 <- filter(ena, year(measurement_date) == 2010)
ena_2011 <- filter(ena, year(measurement_date) == 2011)
ena_2012 <- filter(ena, year(measurement_date) == 2012)
ena_2013 <- filter(ena, year(measurement_date) == 2013)
ena_2014 <- filter(ena, year(measurement_date) == 2014)
ena_2015 <- filter(ena, year(measurement_date) == 2015)
ena_2016 <- filter(ena, year(measurement_date) == 2016)
ena_2017 <- filter(ena, year(measurement_date) == 2017)
ena_2018 <- filter(ena, year(measurement_date) == 2018)

```

Checking uniques IDs whose observation has been taken continuously from 2007 to 2018

```{r}

a_07_08 <- subset(ena_2007, ID %in% ena_2008$ID)
a_07_09 <- subset(a_07_08, ID %in% ena_2009$ID)
a_07_10 <- subset(a_07_09, ID %in% ena_2010$ID)
a_07_11 <- subset(a_07_10, ID %in% ena_2011$ID)
a_07_12 <- subset(a_07_11, ID %in% ena_2012$ID)
a_07_13 <- subset(a_07_12, ID %in% ena_2013$ID)
a_07_14 <- subset(a_07_13, ID %in% ena_2014$ID)
a_07_15 <- subset(a_07_14, ID %in% ena_2015$ID)
a_07_16 <- subset(a_07_15, ID %in% ena_2016$ID)
a_07_17 <- subset(a_07_16, ID %in% ena_2017$ID)
a_07_18 <- subset(a_07_17, ID %in% ena_2018$ID)

#a_07_18 <- kids data of 2007 whose obeservation were taken till the end of 2018 without any miss. 

a_unique_07<- subset(ena, ID %in% a_07_18$ID)

#a_unique_07 = All data of the a_07_18 dataset kids from 2007 to 2018.

#Measumements taken on Oct
Oct_07<-a_unique_07 %>% filter(month(measurement_date) %in% c(10))
by_year_cat_Oct_07<-Oct_07 %>% group_by(year, z_cat_WHO) %>% summarise(count=n())

ggplot(by_year_cat_Oct_07)+
  geom_col(aes(x=z_cat_WHO,y=count))+
  facet_wrap(~year)

Prop_07_18_Oct<-by_year_cat_Oct_07 %>% group_by(year) %>% 
            summarise(total=sum(count)) %>% 
            merge(., by_year_cat_Oct_07, all.y=TRUE) %>%
            mutate(Proportion=count*100/total) %>%
            select(year, z_cat_WHO, count, Proportion)


#Measumements taken on April
Apr_07<-a_unique_07 %>% filter(month(measurement_date) %in% c(4))
by_year_cat_Apr_07<-Apr_07 %>% group_by(year, z_cat_WHO) %>% summarise(count=n())

ggplot(by_year_cat_Apr_07)+
  geom_col(aes(x=z_cat_WHO,y=count))+
  facet_wrap(~year)

Prop_07_18_Apr<-by_year_cat_Apr_07 %>% group_by(year) %>% 
                summarise(total=sum(count)) %>% 
                merge(., by_year_cat_Apr_07, all.y=TRUE) %>%
                mutate(Proportion=count*100/total) %>%
                select(year, z_cat_WHO, count, Proportion)


#Checking the number of age counts in 2007
age_check_07 <- a_07_18 %>% group_by(age_bin, year) %>% summarise(count=n())

```



```{r}



```



```{r}



```



```{r}
#Checking height
#Checking the Shortest and Tallest in 2007 and check throughout growth
#Checking 5 shortest heights in 2007 (boy and girl)
shortest_07_boy <- a_07_18 %>% arrange(height_cm) %>% filter((gender) %in% c("boy"))%>% head(5)
shortest_07_boy_IDs<-shortest_07_boy$ID

shortest_07_girl <- a_07_18 %>% arrange(height_cm) %>% filter((gender) %in% c("girl")) %>% head(5)
shortest_07_girl_IDs<-shortest_07_girl$ID

#Checking prop increase per year
a_unique_07_pct<-a_unique_07 %>%
  group_by(ID) %>% 
  arrange(measurement_date, .by_group = TRUE) %>%
  mutate(pct_change = (height_cm/lag(height_cm) - 1) * 100) %>% 
  select(ID, measurement_date, height_cm, pct_change)

#Checking growth rate of the shortest kids from 2007 throught 2018
#BOY
shortest_boy<-a_unique_07_pct %>% filter((ID) %in% c(shortest_07_boy_IDs)) %>% 
  select(ID, measurement_date, height_cm, pct_change)

ggplot(shortest_boy, aes(x=measurement_date, y = pct_change ))+
  geom_line()+facet_wrap(~ID)+
  geom_hline(yintercept=0, linetype="dashed", color = "red")

#GIRL
shortest_girl<-a_unique_07_pct %>% filter((ID) %in% c(shortest_07_girl_IDs)) %>% 
  select(ID, measurement_date, height_cm, pct_change)

ggplot(shortest_girl, aes(x=measurement_date, y = pct_change ))+
  geom_line()+facet_wrap(~ID)+
  geom_hline(yintercept=0, linetype="dashed", color = "red")

#Negative growth rate check (Wrong Data)
shortest_girl%>% filter((ID)%in%c(262))

```



```{r}

#Checking 5 tallest heights in 2007 (boy and girl)

tallest_07_boy <- a_07_18 %>% arrange(desc(height_cm)) %>% filter((gender) %in% c("boy"))%>% head(5)
tallest_07_boy_IDs<-tallest_07_boy$ID

tallest_07_girl <- a_07_18 %>% arrange(desc(height_cm)) %>% filter((gender) %in% c("girl")) %>% head(5)
tallest_07_girl_IDs<-tallest_07_girl$ID

#Checking growth rate of the shortest kids from 2007 throught 2018
#BOY
tallest_boy<-a_unique_07_pct %>% filter((ID) %in% c(tallest_07_boy_IDs)) %>% 
  select(ID, measurement_date, height_cm, pct_change)

ggplot(tallest_boy, aes(x=measurement_date, y = pct_change ))+
  geom_line()+facet_wrap(~ID)+
  geom_hline(yintercept=0, linetype="dashed", color = "red")

#GIRL
tallest_girl<-a_unique_07_pct %>% filter((ID) %in% c(tallest_07_girl_IDs)) %>% 
  select(ID, measurement_date, height_cm, pct_change)

ggplot(tallest_girl, aes(x=measurement_date, y = pct_change ))+
  geom_line()+facet_wrap(~ID)+
  geom_hline(yintercept=0, linetype="dashed", color = "red")

#Negative growth rate check (Wrong Data)
tallest_girl%>% filter((ID)%in%c(340))

```



```{r}

#Checking the height in 2018 and investigating their growth from 2007 to 2018.
#Checking the Shortest and Tallest in 2018 and check throughout growth

#Finding IDs of the shortest kids on 2018
shortest_boy_18<-a_unique_07 %>% filter((year(measurement_date)) %in% c(2018)) %>% 
  arrange(height_cm) %>% filter((gender) %in% c("boy")) %>% head(5)
shortest_boy_18_IDs <-shortest_boy_18$ID

shortest_girl_18<-a_unique_07 %>% filter((year(measurement_date)) %in% c(2018)) %>% 
  arrange(height_cm) %>% filter((gender) %in% c("girl")) %>% head(5)
shortest_girl_18_IDs <-shortest_girl_18$ID

#Checking growth rate of the shortest kids from 2007 throught 2018
#BOY
shortest_boy_all<-a_unique_07_pct %>% filter((ID) %in% c(shortest_boy_18_IDs)) %>% 
  select(ID, measurement_date, height_cm, pct_change)

ggplot(shortest_boy_all, aes(x=measurement_date, y = pct_change ))+
  geom_line()+facet_wrap(~ID)+
  geom_hline(yintercept=0, linetype="dashed", color = "red")

#GIRL
shortest_girl_all<-a_unique_07_pct %>% filter((ID) %in% c(shortest_girl_18_IDs)) %>% 
  select(ID, measurement_date, height_cm, pct_change)

ggplot(shortest_girl_all, aes(x=measurement_date, y = pct_change ))+
  geom_line()+facet_wrap(~ID)+
  geom_hline(yintercept=0, linetype="dashed", color = "red")

#Negative growth rate check (Wrong Data)
shortest_girl_all%>% filter((ID)%in%c(262))

```
```{r}
#Checking the height in 2018 and investigating their growth from 2007 to 2018.

#Finding IDs of the tallest kids on 2018
tallest_boy_18<-a_unique_07 %>% filter((year(measurement_date)) %in% c(2018)) %>% 
  arrange(desc(height_cm)) %>% filter((gender) %in% c("boy")) %>% head(5)
tallest_boy_18_IDs <-tallest_boy_18$ID

tallest_girl_18<-a_unique_07 %>% filter((year(measurement_date)) %in% c(2018)) %>% 
  arrange(desc(height_cm)) %>% filter((gender) %in% c("girl")) %>% head(5)
tallest_girl_18_IDs <-tallest_girl_18$ID

#Checking growth rate of the shortest kids from 2007 throught 2018
#BOY
tallest_boy_all<-a_unique_07_pct %>% filter((ID) %in% c(tallest_boy_18_IDs)) %>% 
  select(ID, measurement_date, height_cm, pct_change)

ggplot(tallest_boy_all, aes(x=measurement_date, y = pct_change ))+
  geom_line()+facet_wrap(~ID)+
  geom_hline(yintercept=0, linetype="dashed", color = "red")

#GIRL
tallest_girl_all<-a_unique_07_pct %>% filter((ID) %in% c(tallest_girl_18_IDs)) %>% 
  select(ID, measurement_date, height_cm, pct_change)

ggplot(tallest_girl_all, aes(x=measurement_date, y = pct_change ))+
  geom_line()+facet_wrap(~ID)+
  geom_hline(yintercept=0, linetype="dashed", color = "red")

#Negative growth rate check (Wrong Data)
tallest_girl_all%>% filter((ID)%in%c(898))


```


```{r}

#Checking growth of all boys and girls combined
mod <- sitar(x = age_years, y = height_cm, id = ID, data = a_unique_07, df = 5)
par(mar = c(4,4,1,1) + 0.1, cex = 0.8)

#Growth curve for all IDs 
mplot(x = age_years, y = height_cm, id = ID, data = a_unique_07, col = ID, las = 1)
plot(mod, opt = 'a', col = ID, las = 1, xlim = xaxsd(), ylim = yaxsd())

#Growth curve for all IDs by boys and girls
mplot(x = age_years, y = height_cm, id = ID, data = a_unique_07, col = gender, las = 1)
plot(mod, opt = 'a', col = gender, las = 1, xlim = xaxsd(), ylim = yaxsd())
legend("bottomleft", legend=c("Black -> Boys", "Red -> Girls"), col=c("red", "blue"))


par(mar = c(4,4,1,1) + 0.1, cex = 0.8)
plot(mod, opt = 'd', las = 1, apv = TRUE)
plot(mod, opt = 'v', las = 1, apv = TRUE, lty = 2)

par(mar = c(4,4,1,1) + 0.1, cex = 0.8)
plot(mod, opt = 'u', las = 1, col = 8, lwd = 0.5)
lines(mod, opt = 'd', lty = 2)
lines(mod, opt = 'ua', col = 4, subset = ID == 312)
lines(mod, opt = 'ua', col = 2, subset = ID == 277)
lines(mod, opt = 'ua', col = 6, subset = ID == 299)
lines(mod, opt = 'ua', col = 3, subset = ID == 310)
lines(mod, opt = 'ua', col = 1, subset = ID == 3387)
legend('bottomright', c('ID 312', 'ID 277','ID 299','ID 310','ID 3387','mean'),lty = c(1,1,1,1,1,2), col = c(4,2,6,3,8), cex = 0.8, inset=0.04)

pairs(ranef(mod), labels = c('size', 'timing', 'intensity'), pch=20)

```



```{r}

#Dividing a_07_18 : boys and girls and show the growth curve : making 2 datasets from a_unique_07 (boys and girls) and fiting sitar

only_boy_07_18<-a_07_18 %>% filter((gender) %in% c('boy'))
boy_ID<-only_boy_07_18$ID
only_girl_07_18<-a_07_18 %>% filter((gender) %in% c('girl'))
girl_ID<-only_girl_07_18$ID
a_unique_07_boy<-a_unique_07 %>% filter((ID) %in% c(boy_ID))
a_unique_07_girl<-a_unique_07 %>% filter((ID) %in% c(girl_ID))

#Checking growth of only boys
mod_boy <- sitar(x = age_years, y = height_cm, id = ID, data = a_unique_07_boy, df = 5)
par(mar = c(4,4,1,1) + 0.1, cex = 0.8)

#Growth curve for all boys IDs 
mplot(x = age_years, y = height_cm, id = ID, data = a_unique_07_boy, col = ID, las = 1)
plot(mod_boy, opt = 'a', col = ID, las = 1, xlim = xaxsd(), ylim = yaxsd())


par(mar = c(4,4,1,1) + 0.1, cex = 0.8)
plot(mod_boy, opt = 'd', las = 1, apv = TRUE)
plot(mod_boy, opt = 'v', las = 1, apv = TRUE, lty = 2)

par(mar = c(4,4,1,1) + 0.1, cex = 0.8)
plot(mod_boy, opt = 'u', las = 1, col = 8, lwd = 0.5)
lines(mod_boy, opt = 'd', lty = 2)


pairs(ranef(mod_boy), labels = c('size', 'timing', 'intensity'), pch=20)

```

```{r}

#Checking growth of only girls
mod_girl <- sitar(x = age_years, y = height_cm, id = ID, data = a_unique_07_girl, df = 5)
par(mar = c(4,4,1,1) + 0.1, cex = 0.8)

#Growth curve for all boys IDs 
mplot(x = age_years, y = height_cm, id = ID, data = a_unique_07_girl, col = ID, las = 1)
plot(mod_girl, opt = 'a', col = ID, las = 1, xlim = xaxsd(), ylim = yaxsd())


par(mar = c(4,4,1,1) + 0.1, cex = 0.8)
plot(mod_girl, opt = 'd', las = 1, apv = TRUE)
plot(mod_girl, opt = 'v', las = 1, apv = TRUE, lty = 2)

par(mar = c(4,4,1,1) + 0.1, cex = 0.8)
plot(mod_girl, opt = 'u', las = 1, col = 8, lwd = 0.5)
lines(mod_girl, opt = 'd', lty = 2)


pairs(ranef(mod_girl), labels = c('size', 'timing', 'intensity'), pch=20)

```



```{r}
e_normal<-read_excel("~/SharedFiles/ST606/2020/data/Exercise/fit_database_exercise_normal.xlsx", na="NA")
ena_normal <- na.omit(e_normal)
nrow(ena_normal)

colnames(ena_normal)

#And Compare both shortest and tallest
#check weight and BMI and heartrate as well


```
