---
title: "Exercise_D"
author: "Sankhadip"
date: "4/24/2020"
output: html_document
---

```{r, eval=T, echo=FALSE}
suppressMessages(library(tidyverse))
suppressMessages(library(ggplot2))
suppressMessages(library(GGally))
library(lubridate)
library(readxl)
library(plotly)
library(lubridate)

```

Renaming Column Names for easy code handling and Cleaning Data

```{r}
e <- read_excel("~/SharedFiles/ST606/2020/data/Exercise/fit_database_anthropometric_all.xlsx")


#Renaming Variables

names(e)[names(e)=='measurement date']<- 'measurement_date'
names(e)[names(e)=='age (years)']<- 'age_years'
names(e)[names(e)=='age bin']<- 'age_bin'
#names(e)[names(e)=='z-category (WHO)']<- 'z_cat_WHO'
names(e)[length(e)]<-"z_cat_WHO"
names(e)[9]<-"z_score_WHO"
names(e)[6]<-"height_cm"
names(e)[7]<-"weight_kg"

#Dealing with NAs
ena<-na.omit(e)
any(is.na(ena$z_cat_WHO))

```


```{r}

#Changing Data Types
ena <- ena %>%
  mutate(gender = as.factor(gender),
         z_cat_WHO=as.factor(z_cat_WHO),
         measurement_date=as.Date(measurement_date),
         BMI = as.numeric(BMI),
         z_score_WHO=as.numeric(z_score_WHO),
         height_cm=as.numeric(height_cm),
         weight_kg=as.numeric(weight_kg))

#Removing "NA" Characters
ena$observation <- 1:nrow(ena)
x<-ena[ena$z_cat_WHO=="NA",]
y<-x$observation
ena<-ena[-y,]

#Adding additional column
ena$year <- year(ena$measurement_date)

```

Diving data as per Year

```{r}

ena_2007 <- filter(ena, year(measurement_date) == 2007)
ena_2008 <- filter(ena, year(measurement_date) == 2008)
ena_2009 <- filter(ena, year(measurement_date) == 2009)
ena_2010 <- filter(ena, year(measurement_date) == 2010)
ena_2011 <- filter(ena, year(measurement_date) == 2011)
ena_2012 <- filter(ena, year(measurement_date) == 2012)
ena_2013 <- filter(ena, year(measurement_date) == 2013)
ena_2014 <- filter(ena, year(measurement_date) == 2014)
ena_2015 <- filter(ena, year(measurement_date) == 2015)
ena_2016 <- filter(ena, year(measurement_date) == 2016)
ena_2017 <- filter(ena, year(measurement_date) == 2017)
ena_2018 <- filter(ena, year(measurement_date) == 2018)

```

Checking uniques IDs whose observation has been taken continuously from 2007 to 2018

```{r}

a_07_08 <- subset(ena_2007, ID %in% ena_2008$ID)
a_07_09 <- subset(a_07_08, ID %in% ena_2009$ID)
a_07_10 <- subset(a_07_09, ID %in% ena_2010$ID)
a_07_11 <- subset(a_07_10, ID %in% ena_2011$ID)
a_07_12 <- subset(a_07_11, ID %in% ena_2012$ID)
a_07_13 <- subset(a_07_12, ID %in% ena_2013$ID)
a_07_14 <- subset(a_07_13, ID %in% ena_2014$ID)
a_07_15 <- subset(a_07_14, ID %in% ena_2015$ID)
a_07_16 <- subset(a_07_15, ID %in% ena_2016$ID)
a_07_17 <- subset(a_07_16, ID %in% ena_2017$ID)
a_07_18 <- subset(a_07_17, ID %in% ena_2018$ID)

a_unique_07<- subset(ena, ID %in% a_07_18$ID)

#Measumements taken on Oct
Oct_07<-a_unique_07 %>% filter(month(measurement_date) %in% c(10))
by_year_cat_Oct_07<-Oct_07 %>% group_by(year, z_cat_WHO) %>% summarise(count=n())

ggplot(by_year_cat_Oct_07)+
  geom_col(aes(x=z_cat_WHO,y=count))+
  facet_wrap(~year)

Prop_07_18_Oct<-by_year_cat_Oct_07 %>% group_by(year) %>% 
            summarise(total=sum(count)) %>% 
            merge(., by_year_cat_Oct_07, all.y=TRUE) %>%
            mutate(Proportion=count*100/total) %>%
            select(year, z_cat_WHO, count, Proportion)


#Measumements taken on April
Apr_07<-a_unique_07 %>% filter(month(measurement_date) %in% c(4))
by_year_cat_Apr_07<-Apr_07 %>% group_by(year, z_cat_WHO) %>% summarise(count=n())

ggplot(by_year_cat_Apr_07)+
  geom_col(aes(x=z_cat_WHO,y=count))+
  facet_wrap(~year)

Prop_07_18_Apr<-by_year_cat_Apr_07 %>% group_by(year) %>% 
                summarise(total=sum(count)) %>% 
                merge(., by_year_cat_Apr_07, all.y=TRUE) %>%
                mutate(Proportion=count*100/total) %>%
                select(year, z_cat_WHO, count, Proportion)


#Checking the number of age counts in 2007
age_check_07 <- a_07_18 %>% group_by(age_bin, year) %>% summarise(count=n())


```

Checking Uniques IDs whose observation has been taken continuously from 2008 to 2018

```{r}

a_08_09 <- subset(ena_2008, ID %in% ena_2009$ID)
a_08_10 <- subset(a_08_09, ID %in% ena_2010$ID)
a_08_11 <- subset(a_08_10, ID %in% ena_2011$ID)
a_08_12 <- subset(a_08_11, ID %in% ena_2012$ID)
a_08_13 <- subset(a_08_12, ID %in% ena_2013$ID)
a_08_14 <- subset(a_08_13, ID %in% ena_2014$ID)
a_08_15 <- subset(a_08_14, ID %in% ena_2015$ID)
a_08_16 <- subset(a_08_15, ID %in% ena_2016$ID)
a_08_17 <- subset(a_08_16, ID %in% ena_2017$ID)
a_08_18 <- subset(a_08_17, ID %in% ena_2018$ID)

nrow(a_08_18)

a_unique_08<- subset(ena, ID %in% a_08_18$ID)

a_check_08<-ggplot(data=a_unique_08)+
  geom_bar(aes(x=z_cat_WHO))+facet_wrap(~year(measurement_date))

ggplotly(a_check_08)

nrow(a_unique_08)

a_08_18 %>% group_by(ID, year) %>% summarise(count=n()) -> dat_08
a_08_18 %>% group_by(age_bin, year) %>% summarise(count=n()) -> age_check_08
obese_check_08<-a_unique_08 %>% group_by(year, z_cat_WHO) %>% summarise(count=n())

a_08_18<-a_08_18[a_08_18$measurement_date=="2008-10-01",]
nrow(a_08_18)

cat_num_08<-a_08_18 %>% group_by(z_cat_WHO) %>% summarise(count=n())
cat_num_08$prop <- round(cat_num_08$count*100/sum(cat_num_08$count))

```

Checking Uniques IDs whose observation has been taken continuously from 2009 to 2018

```{r}

a_09_10 <- subset(ena_2009, ID %in% ena_2010$ID)
a_09_11 <- subset(a_09_10, ID %in% ena_2011$ID)
a_09_12 <- subset(a_09_11, ID %in% ena_2012$ID)
a_09_13 <- subset(a_09_12, ID %in% ena_2013$ID)
a_09_14 <- subset(a_09_13, ID %in% ena_2014$ID)
a_09_15 <- subset(a_09_14, ID %in% ena_2015$ID)
a_09_16 <- subset(a_09_15, ID %in% ena_2016$ID)
a_09_17 <- subset(a_09_16, ID %in% ena_2017$ID)
a_09_18 <- subset(a_09_17, ID %in% ena_2018$ID)

nrow(a_09_18)

a_unique_09<- subset(ena, ID %in% a_09_18$ID)

a_check_09<-ggplot(data=a_unique_09)+
  geom_bar(aes(x=z_cat_WHO))+facet_wrap(~year(measurement_date))

ggplotly(a_check_09)




nrow(a_unique_09)

dat_09 <- a_09_18 %>% group_by(ID, year) %>% summarise(count=n())
age_check_09 <- a_09_18 %>% group_by(age_bin, year) %>% summarise(count=n())
age_check_09
obese_check_09<-a_unique_09 %>% group_by(z_cat_WHO,year) %>% summarise(count=n())
obese_check_09%>% filter(z_cat_WHO=="obese")%>% arrange(desc(count))%>%head(3)


a_unique_09 %>% group_by(year) %>% summarise(count=n())

a_08_18<-a_09_18[a_08_18$measurement_date=="2008-10-01",]
nrow(a_09_18)

cat_num_08<-a_08_18 %>% group_by(z_cat_WHO) %>% summarise(count=n())
cat_num_08$prop <- round(cat_num_08$count*100/sum(cat_num_08$count))



```

```{r,eval=F}

```


```{r}


#count differnt for temp_08 and a_08_18 because some ids took obs on 2007 and not on 2008 so removed those.
#for checking the max of age group by and give predictions

```